# Generated by Django 5.1.15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_blogpostimage"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogpost",
            name="topics",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Список ключевых слов для перелинковки (shacman, самосвал, тягач, лизинг и т.д.). Если пусто — используется эвристика по title/content.",
                verbose_name="Темы / ключевые слова",
            ),
        ),
    ]
