# Generated by Django 4.2.27 on 2025-12-10 11:09

import catalog.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('model_name_ru', models.CharField(max_length=255)),
                ('model_name_en', models.CharField(max_length=255)),
                ('short_description_ru', models.CharField(blank=True, max_length=500)),
                ('short_description_en', models.CharField(blank=True, max_length=500)),
                ('description_ru', catalog.models.RichTextField(blank=True)),
                ('description_en', catalog.models.RichTextField(blank=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('availability', models.CharField(choices=[('IN_STOCK', 'В наличии'), ('ON_REQUEST', 'Под заказ')], default='IN_STOCK', max_length=20)),
                ('engine_model', models.CharField(blank=True, max_length=255)),
                ('power_hp', models.IntegerField(blank=True, null=True)),
                ('wheel_formula', models.CharField(blank=True, max_length=50)),
                ('payload_tons', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('dimensions', models.CharField(blank=True, max_length=255)),
                ('options', models.JSONField(blank=True, default=dict)),
                ('tags', models.JSONField(blank=True, default=list, null=True)),
                ('published', models.BooleanField(default=True)),
                ('views_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='catalog.category')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('description_ru', catalog.models.RichTextField(blank=True)),
                ('description_en', catalog.models.RichTextField(blank=True)),
            ],
            options={
                'verbose_name': 'Серия',
                'verbose_name_plural': 'Серии',
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('telegram_bot_token', models.CharField(blank=True, max_length=255)),
                ('telegram_chat_id', models.CharField(blank=True, max_length=255)),
                ('whatsapp_number', models.CharField(blank=True, max_length=50)),
                ('analytics_code', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Настройки сайта',
                'verbose_name_plural': 'Настройки сайта',
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='products/')),
                ('order', models.PositiveIntegerField(default=0)),
                ('alt_ru', models.CharField(blank=True, max_length=255)),
                ('alt_en', models.CharField(blank=True, max_length=255)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='catalog.product')),
            ],
            options={
                'verbose_name': 'Изображение товара',
                'verbose_name_plural': 'Изображения товаров',
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='series',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='catalog.series'),
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('message', models.TextField(blank=True)),
                ('source', models.CharField(blank=True, max_length=255)),
                ('utm_source', models.CharField(blank=True, max_length=255)),
                ('utm_medium', models.CharField(blank=True, max_length=255)),
                ('utm_campaign', models.CharField(blank=True, max_length=255)),
                ('utm_term', models.CharField(blank=True, max_length=255)),
                ('utm_content', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed', models.BooleanField(default=False)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.product')),
            ],
            options={
                'verbose_name': 'Лид',
                'verbose_name_plural': 'Лиды',
                'ordering': ['-created_at'],
            },
        ),
    ]
