# Generated by Django 4.2.27 on 2025-12-10 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категория Техники', 'verbose_name_plural': 'Категории Техники'},
        ),
        migrations.AlterModelOptions(
            name='lead',
            options={'ordering': ['-created_at'], 'verbose_name': 'Заявка', 'verbose_name_plural': 'Заявки'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-created_at'], 'verbose_name': 'Единица Техники', 'verbose_name_plural': 'Техника'},
        ),
        migrations.AlterModelOptions(
            name='series',
            options={'verbose_name': 'Серия Техники', 'verbose_name_plural': 'Серии Техники'},
        ),
    ]
