# Generated by Django 4.2.27 on 2025-12-10 21:07

import catalog.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_category_options_alter_lead_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название категории'),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='product',
            name='availability',
            field=models.CharField(choices=[('IN_STOCK', 'В наличии'), ('ON_REQUEST', 'Под заказ')], default='IN_STOCK', max_length=20, verbose_name='Наличие'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='catalog.category', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создан'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description_en',
            field=catalog.models.RichTextField(blank=True, verbose_name='Описание (EN)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description_ru',
            field=catalog.models.RichTextField(blank=True, verbose_name='Описание (RU)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='dimensions',
            field=models.CharField(blank=True, max_length=255, verbose_name='Габариты'),
        ),
        migrations.AlterField(
            model_name='product',
            name='engine_model',
            field=models.CharField(blank=True, max_length=255, verbose_name='Модель двигателя'),
        ),
        migrations.AlterField(
            model_name='product',
            name='model_name_en',
            field=models.CharField(max_length=255, verbose_name='Модель (EN)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='model_name_ru',
            field=models.CharField(max_length=255, verbose_name='Модель (RU)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='options',
            field=models.JSONField(blank=True, default=dict, verbose_name='Опции'),
        ),
        migrations.AlterField(
            model_name='product',
            name='payload_tons',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Грузоподъёмность, т'),
        ),
        migrations.AlterField(
            model_name='product',
            name='power_hp',
            field=models.IntegerField(blank=True, null=True, verbose_name='Мощность, л.с.'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='product',
            name='published',
            field=models.BooleanField(default=True, verbose_name='Опубликован'),
        ),
        migrations.AlterField(
            model_name='product',
            name='series',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='catalog.series', verbose_name='Серия'),
        ),
        migrations.AlterField(
            model_name='product',
            name='short_description_en',
            field=models.CharField(blank=True, max_length=500, verbose_name='Краткое описание (EN)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='short_description_ru',
            field=models.CharField(blank=True, max_length=500, verbose_name='Краткое описание (RU)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.CharField(max_length=100, unique=True, verbose_name='Артикул'),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='product',
            name='tags',
            field=models.JSONField(blank=True, default=list, null=True, verbose_name='Теги'),
        ),
        migrations.AlterField(
            model_name='product',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлён'),
        ),
        migrations.AlterField(
            model_name='product',
            name='views_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Просмотры'),
        ),
        migrations.AlterField(
            model_name='product',
            name='wheel_formula',
            field=models.CharField(blank=True, max_length=50, verbose_name='Колёсная формула'),
        ),
        migrations.AlterField(
            model_name='series',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название серии'),
        ),
        migrations.AlterField(
            model_name='series',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='URL'),
        ),
    ]
