# Generated by Django 4.2.27 on 2025-12-11 09:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_category_name_alter_category_slug_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name': 'Категория Техники', 'verbose_name_plural': 'Категории Техники'},
        ),
        migrations.AlterModelOptions(
            name='series',
            options={'ordering': ['name'], 'verbose_name': 'Серия Техники', 'verbose_name_plural': 'Серии Техники'},
        ),
        migrations.AlterField(
            model_name='lead',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='catalog.product'),
        ),
        migrations.AlterField(
            model_name='product',
            name='tags',
            field=models.JSONField(blank=True, default=list, verbose_name='Теги'),
        ),
    ]
