# Generated by Django 5.1.15 on 2025-12-14 18:59

import django.db.models.deletion
import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_seed_sitrak_dayun_and_update_shacman_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='config',
            field=models.TextField(blank=True, default='', verbose_name='Комплектация (норм.)'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активен'),
        ),
        migrations.AddField(
            model_name='product',
            name='model_code',
            field=models.CharField(blank=True, db_index=True, default='', max_length=120, verbose_name='Код модели'),
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Город')),
                ('slug', models.SlugField(unique=True, verbose_name='URL')),
                ('sort_order', models.IntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Город',
                'verbose_name_plural': 'Города',
                'ordering': ['sort_order', 'name'],
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Lower('slug'), name='city_slug_ci_unique')],
            },
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.PositiveIntegerField(default=0, verbose_name='Количество')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Цена')),
                ('currency', models.CharField(blank=True, default='RUB', max_length=10, verbose_name='Валюта')),
                ('vat', models.CharField(blank=True, default='с НДС', max_length=50, verbose_name='НДС')),
                ('year', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Год')),
                ('source_file', models.CharField(blank=True, default='', max_length=255, verbose_name='Файл-источник')),
                ('source_row_hash', models.CharField(blank=True, db_index=True, default='', max_length=64, verbose_name='Хэш строки')),
                ('batch_token', models.CharField(blank=True, db_index=True, default='', max_length=64, verbose_name='Токен импорта')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='offers', to='catalog.city', verbose_name='Город')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='catalog.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Предложение / Остаток',
                'verbose_name_plural': 'Предложения / Остатки',
                'ordering': ['city__sort_order', 'city__name', '-updated_at', '-id'],
                'indexes': [models.Index(fields=['product', 'is_active'], name='offer_product_active_idx'), models.Index(fields=['city', 'is_active'], name='offer_city_active_idx'), models.Index(fields=['source_file', 'batch_token'], name='offer_source_batch_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('price__isnull', False)), fields=('product', 'city', 'price', 'year', 'vat'), name='uniq_offer_key'), models.UniqueConstraint(condition=models.Q(('price__isnull', True)), fields=('product', 'city', 'year', 'vat'), name='uniq_offer_key_null_price')],
            },
        ),
    ]
