# Generated by Django 5.1.15 on 2025-12-17 19:28

import django.db.models.deletion
import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_update_official_texts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='series',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='catalog.series', verbose_name='Бренд'),
        ),
        migrations.CreateModel(
            name='ModelVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название модели')),
                ('slug', models.SlugField(unique=True, verbose_name='URL')),
                ('line', models.CharField(max_length=50, verbose_name='Линейка')),
                ('wheel_formula', models.CharField(max_length=50, verbose_name='Колёсная формула')),
                ('sort_order', models.IntegerField(default=0, verbose_name='Порядок')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='model_variants', to='catalog.series', verbose_name='Бренд')),
            ],
            options={
                'verbose_name': 'Модель / модификация',
                'verbose_name_plural': 'Модели / модификации',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='model_variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='catalog.modelvariant', verbose_name='Модель'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['model_variant', 'published'], name='product_modelvar_pub_idx'),
        ),
        migrations.AddConstraint(
            model_name='modelvariant',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('slug'), name='modelvariant_slug_ci_unique'),
        ),
        migrations.AddConstraint(
            model_name='modelvariant',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), models.F('brand'), name='modelvariant_brand_name_ci_unique'),
        ),
    ]
