# Generated by Django 5.1.15 on 2025-12-17 19:29

from django.db import migrations


def seed_shacman_categories_and_models(apps, schema_editor):
    Series = apps.get_model("catalog", "Series")
    Category = apps.get_model("catalog", "Category")
    ModelVariant = apps.get_model("catalog", "ModelVariant")

    brand = Series.objects.filter(slug__iexact="shacman").first()
    if brand is None:
        brand = Series.objects.create(slug="shacman", name="SHACMAN")
    else:
        brand_update_fields = []
        if (brand.slug or "").lower() == "shacman" and brand.slug != "shacman":
            brand.slug = "shacman"
            brand_update_fields.append("slug")
        if brand.name != "SHACMAN":
            brand.name = "SHACMAN"
            brand_update_fields.append("name")
        if brand_update_fields:
            brand.save(update_fields=brand_update_fields)

    categories = [
        ("samosvaly", "Самосвалы"),
        ("sedelnye-tyagachi", "Седельные тягачи"),
        ("avtobetonosmesiteli", "Автобетоносмесители"),
        ("kmu", "КМУ"),
        ("kdm", "КДМ"),
        ("sortimentovozy", "Сортиментовозы"),
        ("musorovozy", "Мусоровозы"),
        ("bortovye-gruzoviki", "Бортовые грузовики"),
        ("multilifty", "Мультилифты"),
        ("atz", "АТЗ"),
        ("mkdu", "МКДУ"),
        ("lomovozy", "Ломовозы"),
    ]
    for slug, name in categories:
        obj = Category.objects.filter(slug__iexact=slug).first()
        if obj is None:
            Category.objects.create(slug=slug, name=name)
            continue

        update_fields = []
        if (obj.slug or "").lower() == slug and obj.slug != slug:
            obj.slug = slug
            update_fields.append("slug")
        if obj.name != name:
            obj.name = name
            update_fields.append("name")
        if update_fields:
            obj.save(update_fields=update_fields)

    model_variants = [
        (10, "x6000-4x2", "X6000 4x2", "X6000", "4x2"),
        (20, "x6000-6x4", "X6000 6x4", "X6000", "6x4"),
        (30, "x5000-6x4", "X5000 6x4", "X5000", "6x4"),
        (40, "x5000-6x6", "X5000 6x6", "X5000", "6x6"),
        (50, "x5000-8x4", "X5000 8x4", "X5000", "8x4"),
        (60, "x3000-8x4", "X3000 8x4", "X3000", "8x4"),
        (70, "x3000-4x2", "X3000 4x2", "X3000", "4x2"),
        (80, "x3000-6x4", "X3000 6x4", "X3000", "6x4"),
    ]
    for sort_order, slug, name, line, wheel_formula in model_variants:
        obj = ModelVariant.objects.filter(slug__iexact=slug).first()
        if obj is None:
            ModelVariant.objects.create(
                brand=brand,
                slug=slug,
                name=name,
                line=line,
                wheel_formula=wheel_formula,
                sort_order=sort_order,
            )
            continue

        update_fields = []
        if obj.brand_id != brand.id:
            obj.brand = brand
            update_fields.append("brand")
        if (obj.slug or "").lower() == slug and obj.slug != slug:
            obj.slug = slug
            update_fields.append("slug")
        if obj.name != name:
            obj.name = name
            update_fields.append("name")
        if obj.line != line:
            obj.line = line
            update_fields.append("line")
        if obj.wheel_formula != wheel_formula:
            obj.wheel_formula = wheel_formula
            update_fields.append("wheel_formula")
        if getattr(obj, "sort_order", None) != sort_order:
            obj.sort_order = sort_order
            update_fields.append("sort_order")
        if update_fields:
            obj.save(update_fields=update_fields)


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_alter_product_series_modelvariant_and_more'),
    ]

    operations = [
        migrations.RunPython(
            seed_shacman_categories_and_models, migrations.RunPython.noop
        ),
    ]
