# Generated by Django 5.1.15 on 2025-12-22 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_seed_shacman_categories_and_models'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='series',
            options={'ordering': ['name'], 'verbose_name': 'Бренд', 'verbose_name_plural': 'Бренды'},
        ),
        migrations.AlterField(
            model_name='series',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название бренда'),
        ),
    ]
