# Generated by Django 5.1.15 on 2025-12-23 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0014_alter_productimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='cover_alt_ru',
            field=models.CharField(blank=True, default='', help_text='Текст для атрибута alt. Если пусто — будет использовано название категории.', max_length=255, verbose_name='ALT (RU)'),
        ),
        migrations.AddField(
            model_name='category',
            name='cover_image',
            field=models.ImageField(blank=True, help_text='Форматы: .jpg/.jpeg/.png/.webp (.jfif тоже поддерживается как JPEG). Рекомендуем: 16:9, 1600×900 (оптимально), минимум 1200×675. JPG качество 80–85.', null=True, upload_to='categories/', verbose_name='Титульное фото'),
        ),
        migrations.AddField(
            model_name='series',
            name='logo',
            field=models.ImageField(blank=True, help_text='Форматы: .jpg/.jpeg/.png/.webp (.jfif тоже поддерживается как JPEG). Рекомендуем: PNG с прозрачностью, 512×512 (квадрат) или 512×256 (широкий).', null=True, upload_to='brands/', verbose_name='Логотип'),
        ),
        migrations.AddField(
            model_name='series',
            name='logo_alt_ru',
            field=models.CharField(blank=True, default='', help_text='Текст для атрибута alt. Если пусто — будет использовано название бренда.', max_length=255, verbose_name='ALT (RU)'),
        ),
    ]
