# Generated by Django 5.1.15 on 2025-12-23 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0015_category_cover_alt_ru_category_cover_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='map_embed',
            field=models.TextField(blank=True, help_text='HTML-код для встраивания карты (iframe). Опционально.', verbose_name='Код карты (iframe)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='work_hours',
            field=models.CharField(blank=True, help_text='Например: Пн-Пт: 9:00-18:00', max_length=255, verbose_name='Режим работы'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='address',
            field=models.CharField(blank=True, help_text='Адрес офиса или склада. Если пусто — блок адреса на странице контактов не отображается.', max_length=255, verbose_name='Адрес'),
        ),
    ]
