# Generated by Django 5.1.x on 2026-01-12

from __future__ import annotations

import re

from django.db import migrations


_TEMPLATE_COMMENT_RE = re.compile(r"\{#.*?#\}", flags=re.DOTALL)
_INLINE_SVG_RE = re.compile(
    r"Inline\s+SVG\s+placeholder(?:\s+for\s+cases\s+when\s+product\s+has\s+no\s+images)?",
    flags=re.IGNORECASE,
)


def _clean_str(value: object) -> object:
    """
    Remove template artifacts from a string-like DB value.

    Important: keep the transformation minimal/safe for HTML fragments stored in DB.
    """
    if value is None:
        return None
    if value == "":
        return ""

    s = value if isinstance(value, str) else str(value)
    original = s

    # Remove Django template comments that accidentally got stored as raw text.
    s = _TEMPLATE_COMMENT_RE.sub("", s)

    # Remove known placeholder markers seen on prod.
    s = _INLINE_SVG_RE.sub("", s)
    s = s.replace("#####", "")
    # If comment delimiters leaked without a closing tag, strip them too.
    s = s.replace("{#", "").replace("#}", "")

    s = s.strip()
    return s if s != original else original


def _clean_json(value: object) -> object:
    """Recursively clean string values inside JSONField structures."""
    if value is None:
        return None
    if isinstance(value, str):
        return _clean_str(value)
    if isinstance(value, list):
        changed = False
        out: list[object] = []
        for item in value:
            cleaned = _clean_json(item)
            out.append(cleaned)
            if cleaned != item:
                changed = True
        return out if changed else value
    if isinstance(value, dict):
        changed = False
        out: dict[object, object] = {}
        for k, v in value.items():
            cleaned_v = _clean_json(v)
            out[k] = cleaned_v
            if cleaned_v != v:
                changed = True
        return out if changed else value
    return value


def _bulk_clean_queryset(qs, fields: list[str], json_fields: list[str] | None = None) -> int:
    json_fields = json_fields or []
    changed_objects = 0
    for obj in qs.iterator():
        changed_fields: list[str] = []

        for field in fields:
            old = getattr(obj, field, None)
            new = _clean_str(old)
            if new != old:
                setattr(obj, field, new)
                changed_fields.append(field)

        for field in json_fields:
            old = getattr(obj, field, None)
            new = _clean_json(old)
            if new != old:
                setattr(obj, field, new)
                changed_fields.append(field)

        if changed_fields:
            obj.save(update_fields=changed_fields)
            changed_objects += 1
    return changed_objects


def forwards(apps, schema_editor):
    Series = apps.get_model("catalog", "Series")
    Category = apps.get_model("catalog", "Category")
    ModelVariant = apps.get_model("catalog", "ModelVariant")
    Product = apps.get_model("catalog", "Product")
    ProductImage = apps.get_model("catalog", "ProductImage")
    SiteSettings = apps.get_model("catalog", "SiteSettings")

    changed = {}

    changed["Series"] = _bulk_clean_queryset(
        Series.objects.all(),
        fields=["name", "description_ru", "description_en", "history", "logo_alt_ru"],
    )
    changed["Category"] = _bulk_clean_queryset(
        Category.objects.all(),
        fields=["name", "cover_alt_ru"],
    )
    changed["ModelVariant"] = _bulk_clean_queryset(
        ModelVariant.objects.all(),
        fields=["name", "line", "wheel_formula"],
    )
    changed["Product"] = _bulk_clean_queryset(
        Product.objects.all(),
        fields=[
            "model_name_ru",
            "model_name_en",
            "short_description_ru",
            "short_description_en",
            "description_ru",
            "description_en",
            "config",
            "model_code",
        ],
        json_fields=["options", "tags"],
    )
    changed["ProductImage"] = _bulk_clean_queryset(
        ProductImage.objects.all(),
        fields=["alt_ru", "alt_en"],
    )
    changed["SiteSettings"] = _bulk_clean_queryset(
        SiteSettings.objects.all(),
        fields=[
            "email",
            "phone",
            "address",
            "work_hours",
            "map_embed",
            "telegram_chat_id",
            "whatsapp_number",
            "analytics_code",
        ],
    )
    total = sum(changed.values())
    print(f"[0017_clean_template_artifacts] changed_objects_total={total} details={changed}")


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0016_add_site_settings_fields"),
    ]

    operations = [
        migrations.RunPython(forwards, migrations.RunPython.noop),
    ]

