# Generated by Django 5.1.15 on 2026-01-13 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0017_clean_template_artifacts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='cover_image',
            field=models.ImageField(blank=True, help_text='Форматы: .jpg/.jpeg/.png/.webp (.jfif тоже поддерживается как JPEG). Рекомендуем: 16:9, 1600×900 (оптимально) или 1600×600, минимум 1200×675. JPG качество 80–85 или WebP, ≤500 KB.', null=True, upload_to='categories/', verbose_name='Титульное фото'),
        ),
    ]
