# Generated by Django 5.1.15 on 2026-01-13 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0018_alter_category_cover_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='inn',
            field=models.CharField(blank=True, help_text='ИНН организации', max_length=20, verbose_name='ИНН'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='legal_address',
            field=models.TextField(blank=True, help_text='Полный юридический адрес организации', verbose_name='Юридический адрес'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='office_address_1',
            field=models.TextField(blank=True, help_text='Первый фактический адрес (офис/склад)', verbose_name='Фактический адрес 1'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='office_address_2',
            field=models.TextField(blank=True, help_text='Второй фактический адрес (офис/склад)', verbose_name='Фактический адрес 2'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='ogrn',
            field=models.CharField(blank=True, help_text='ОГРН организации', max_length=20, verbose_name='ОГРН'),
        ),
    ]
