# Generated by Django 5.1.15 on 2026-01-14 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0019_add_site_settings_requisites_addresses'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='wheelbase_mm',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Колёсная база, мм'),
        ),
    ]
