# Generated by Django 5.1.15 on 2026-01-19 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0021_alter_product_slug_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(max_length=80, unique=True, verbose_name='URL'),
        ),
    ]
