# Generated by Django 5.1.15 on 2026-01-28 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0025_add_in_stock_seo_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='seo_faq',
            field=models.TextField(blank=True, help_text='FAQ для страницы /catalog/category/<slug>/ в формате JSON-LD FAQPage schema. Формат: один вопрос-ответ на строку, разделитель «|». Пример:\nКакие сроки поставки?|Сроки зависят от наличия техники.\nКакие варианты оплаты?|Работаем с различными вариантами оплаты.', verbose_name='SEO FAQ (витрина категории)'),
        ),
        migrations.AlterField(
            model_name='series',
            name='seo_faq',
            field=models.TextField(blank=True, help_text='FAQ для страницы /catalog/series/<slug>/ в формате JSON-LD FAQPage schema. Формат: один вопрос-ответ на строку, разделитель «|». Пример:\nКакие сроки поставки?|Сроки зависят от наличия техники.\nКакие варианты оплаты?|Работаем с различными вариантами оплаты.', verbose_name='SEO FAQ (витрина бренда)'),
        ),
        migrations.AlterField(
            model_name='seriescategoryseo',
            name='seo_faq',
            field=models.TextField(blank=True, help_text='FAQ для страницы /catalog/series/<series>/<category>/ в формате JSON-LD FAQPage schema. Формат: один вопрос-ответ на строку, разделитель «|». Пример:\nКакие сроки поставки?|Сроки зависят от наличия техники.\nКакие варианты оплаты?|Работаем с различными вариантами оплаты.', verbose_name='SEO FAQ'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='in_stock_seo_faq',
            field=models.TextField(blank=True, help_text='FAQ для страницы /catalog/in-stock/ в формате JSON-LD FAQPage schema. Формат: один вопрос-ответ на строку, разделитель «|». Пример:\nКакие сроки поставки?|Сроки зависят от наличия техники.\nКакие варианты оплаты?|Работаем с различными вариантами оплаты.\nКак оформить заказ?|Заполните форму на сайте или свяжитесь с нами.', verbose_name='SEO FAQ: В наличии'),
        ),
    ]
