# Generated by Django 5.1.15 on 2026-01-29 12:00

import catalog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0026_alter_seo_faq_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='seo_description_override',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='SEO description (переопределение)'),
        ),
        migrations.AddField(
            model_name='product',
            name='seo_faq_override',
            field=models.TextField(blank=True, default='', help_text='Формат: один вопрос-ответ на строку, разделитель «|». Пример: Какие сроки поставки?|Сроки зависят от наличия.', verbose_name='SEO FAQ (переопределение)'),
        ),
        migrations.AddField(
            model_name='product',
            name='seo_text_override',
            field=catalog.models.RichTextField(blank=True, default='', verbose_name='SEO текст (переопределение)'),
        ),
        migrations.AddField(
            model_name='product',
            name='seo_title_override',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='SEO title (переопределение)'),
        ),
    ]
