# Generated by Django 5.1.15 on 2026-01-29 14:02

import catalog.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0027_add_product_seo_override_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShacmanHubSEO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hub_type', models.CharField(choices=[('main', 'Главный хаб /shacman/'), ('in_stock', 'В наличии /shacman/in-stock/'), ('category', 'Категория /shacman/<category>/'), ('category_in_stock', 'Категория в наличии /shacman/<category>/in-stock/')], max_length=32, verbose_name='Тип хаба')),
                ('meta_title', models.CharField(blank=True, default='', max_length=255, verbose_name='SEO Title')),
                ('meta_description', models.CharField(blank=True, default='', max_length=500, verbose_name='Meta Description')),
                ('seo_text', catalog.models.RichTextField(blank=True, default='', help_text='Блоки: Купить SHACMAN, В наличии, Лизинг, Доставка, Гарантия/сервис, Как получить КП, FAQ. HTML допускается.', verbose_name='SEO-текст (900–1500 слов)')),
                ('faq', models.TextField(blank=True, default='', help_text='Один вопрос-ответ на строку, разделитель «|». Пример: Какие сроки?|Сроки зависят от наличия.', verbose_name='FAQ (вопрос | ответ на строку)')),
                ('also_search_line', models.CharField(blank=True, default='', help_text='Например: Также ищут: Шакман / Shacman / Shaanxi', max_length=255, verbose_name='Варианты написания (1 строка)')),
                ('category', models.ForeignKey(blank=True, help_text='Только для типа «категория» / «категория в наличии».', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shacman_hub_seo', to='catalog.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'SEO хаб SHACMAN',
                'verbose_name_plural': 'SEO хабы SHACMAN',
                'ordering': ['hub_type', 'category__name'],
                'constraints': [models.UniqueConstraint(fields=('hub_type', 'category'), name='shacman_hub_seo_type_category_unique')],
            },
        ),
    ]
