# Generated by Django 5.1.15

from django.db import migrations, models
from django.db.models import Q


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0028_add_shacman_hub_seo"),
    ]

    operations = [
        migrations.AddField(
            model_name="shacmanhubseo",
            name="facet_key",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Для formula/engine/line: значение формулы, slug двигателя или линейки (например 8x4, wp13-550e501, x3000).",
                max_length=255,
                verbose_name="Фасет (formula / engine_slug / line_slug)",
            ),
        ),
        migrations.AddField(
            model_name="shacmanhubseo",
            name="seo_intro_html",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Короткий блок над листингом. Допускаются теги: p, strong, em, a, ul, ol, li.",
                verbose_name="SEO-интро (над карточками)",
            ),
        ),
        migrations.AddField(
            model_name="shacmanhubseo",
            name="seo_body_html",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Развёрнутый блок под листингом. Допускаются теги: p, strong, em, a, ul, ol, li, h2, h3.",
                verbose_name="SEO-блок под карточками",
            ),
        ),
        migrations.AlterField(
            model_name="shacmanhubseo",
            name="hub_type",
            field=models.CharField(
                choices=[
                    ("main", "Главный хаб /shacman/"),
                    ("in_stock", "В наличии /shacman/in-stock/"),
                    ("category", "Категория /shacman/<category>/"),
                    ("category_in_stock", "Категория в наличии /shacman/<category>/in-stock/"),
                    ("formula", "Формула /shacman/formula/<formula>/"),
                    ("formula_in_stock", "Формула в наличии /shacman/formula/<formula>/in-stock/"),
                    ("engine", "Двигатель /shacman/engine/<engine>/"),
                    ("engine_in_stock", "Двигатель в наличии /shacman/engine/<engine>/in-stock/"),
                    ("line", "Линейка /shacman/line/<line>/"),
                    ("line_in_stock", "Линейка в наличии /shacman/line/<line>/in-stock/"),
                ],
                max_length=32,
                verbose_name="Тип хаба",
            ),
        ),
        migrations.AddConstraint(
            model_name="shacmanhubseo",
            constraint=models.UniqueConstraint(
                condition=~Q(facet_key=""),
                fields=("hub_type", "facet_key"),
                name="shacman_hub_seo_type_facet_unique",
            ),
        ),
    ]
