# Generated by Django 5.1.15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0029_shacman_hub_seo_facet_intro_body"),
    ]

    operations = [
        migrations.AddField(
            model_name="series",
            name="seo_intro_html",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Короткий блок над сеткой карточек. Допускаются теги: p, strong, em, a, ul, ol, li.",
                verbose_name="SEO-интро (над карточками)",
            ),
        ),
        migrations.AddField(
            model_name="series",
            name="seo_body_html",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Развёрнутый блок под сеткой карточек. Допускаются теги: p, strong, em, a, ul, ol, li, h2, h3.",
                verbose_name="SEO-блок под карточками",
            ),
        ),
        migrations.AddField(
            model_name="category",
            name="seo_intro_html",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Короткий блок над сеткой карточек. Допускаются теги: p, strong, em, a, ul, ol, li.",
                verbose_name="SEO-интро (над карточками)",
            ),
        ),
        migrations.AddField(
            model_name="category",
            name="seo_body_html",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Развёрнутый блок под сеткой карточек. Допускаются теги: p, strong, em, a, ul, ol, li, h2, h3.",
                verbose_name="SEO-блок под карточками",
            ),
        ),
        migrations.AddField(
            model_name="seriescategoryseo",
            name="seo_intro_html",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Короткий блок над сеткой карточек. Допускаются теги: p, strong, em, a, ul, ol, li.",
                verbose_name="SEO-интро (над карточками)",
            ),
        ),
        migrations.AddField(
            model_name="seriescategoryseo",
            name="seo_body_html",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Развёрнутый блок под сеткой карточек. Допускаются теги: p, strong, em, a, ul, ol, li, h2, h3.",
                verbose_name="SEO-блок под карточками",
            ),
        ),
    ]
