# Generated by Django 5.1.15 on 2026-01-30 20:56

import catalog.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0030_catalog_seo_intro_body'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shacmanhubseo',
            options={'ordering': ['hub_type', 'facet_key', 'category__name'], 'verbose_name': 'SEO хаб SHACMAN', 'verbose_name_plural': 'SEO хабы SHACMAN'},
        ),
        migrations.AlterField(
            model_name='shacmanhubseo',
            name='seo_body_html',
            field=catalog.models.RichTextField(blank=True, default='', help_text='Развёрнутый блок под листингом. Допускаются теги: p, strong, em, a, ul, ol, li, h2, h3.', verbose_name='SEO-блок под карточками'),
        ),
        migrations.AlterField(
            model_name='shacmanhubseo',
            name='seo_intro_html',
            field=catalog.models.RichTextField(blank=True, default='', help_text='Короткий блок над листингом. Допускаются теги: p, strong, em, a, ul, ol, li.', verbose_name='SEO-интро (над карточками)'),
        ),
    ]
