# Generated by Django 5.1.15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0031_alter_shacmanhubseo_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="canonical_product",
            field=models.ForeignKey(
                blank=True,
                help_text="Если задан — страница этого товара отдаёт 301 на канонический. В sitemap не попадает.",
                null=True,
                on_delete=models.SET_NULL,
                related_name="aliases",
                to="catalog.product",
                verbose_name="Канонический товар",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="redirect_to_url",
            field=models.URLField(
                blank=True,
                default="",
                help_text="Если задан — страница отдаёт 301 на этот URL (хаб/внешняя страница). В sitemap не попадает.",
                max_length=500,
                verbose_name="Редирект на URL",
            ),
        ),
    ]
