# Generated by Django 5.1.15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0032_product_canonical_redirect"),
    ]

    operations = [
        migrations.CreateModel(
            name="StaticPageSEO",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "slug",
                    models.SlugField(
                        help_text="Совпадает со slug страницы: leasing, used, service, parts, payment-delivery.",
                        max_length=100,
                        unique=True,
                        verbose_name="Slug страницы",
                    ),
                ),
                (
                    "meta_title",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=255,
                        verbose_name="Meta Title (переопределение)",
                    ),
                ),
                (
                    "meta_description",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=500,
                        verbose_name="Meta Description (переопределение)",
                    ),
                ),
                (
                    "seo_intro_html",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Короткий блок над основным контентом страницы. HTML допускается.",
                        verbose_name="SEO-интро (над контентом)",
                    ),
                ),
                (
                    "seo_body_html",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Развёрнутый блок внизу страницы. HTML допускается.",
                        verbose_name="SEO-блок внизу страницы",
                    ),
                ),
                (
                    "faq_items",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text=(
                            "Один вопрос-ответ на строку, разделитель «|». "
                            "Пример: Какие сроки поставки?|Сроки зависят от наличия. "
                            "Рекомендуется 5–10 вопросов для FAQPage schema."
                        ),
                        verbose_name="FAQ (вопрос | ответ на строку)",
                    ),
                ),
            ],
            options={
                "verbose_name": "SEO статической страницы",
                "verbose_name_plural": "SEO статических страниц",
                "ordering": ["slug"],
            },
        ),
    ]
