# Generated by Django 5.1.15

from django.db import migrations, models
from django.db.models import Q


def _hub_type_choices_before():
    return [
        ("main", "Главный хаб /shacman/"),
        ("in_stock", "В наличии /shacman/in-stock/"),
        ("category", "Категория /shacman/<category>/"),
        ("category_in_stock", "Категория в наличии /shacman/<category>/in-stock/"),
        ("formula", "Формула /shacman/formula/<formula>/"),
        ("formula_in_stock", "Формула в наличии /shacman/formula/<formula>/in-stock/"),
        ("engine", "Двигатель /shacman/engine/<engine>/"),
        ("engine_in_stock", "Двигатель в наличии /shacman/engine/<engine>/in-stock/"),
        ("line", "Линейка /shacman/line/<line>/"),
        ("line_in_stock", "Линейка в наличии /shacman/line/<line>/in-stock/"),
    ]


def _hub_type_choices_after():
    return _hub_type_choices_before() + [
        ("category_line", "Категория + линейка /shacman/category/<cat>/line/<line>/"),
        ("category_line_in_stock", "Категория + линейка в наличии"),
        ("line_formula", "Линейка + формула /shacman/line/<line>/formula/<formula>/"),
        ("line_formula_in_stock", "Линейка + формула в наличии"),
        ("category_formula_explicit", "Категория + формула /shacman/category/<cat>/formula/<formula>/"),
        ("category_formula_explicit_in_stock", "Категория + формула в наличии"),
    ]


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0034_cataloglanding_seo"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="shacmanhubseo",
            name="shacman_hub_seo_type_category_unique",
        ),
        migrations.RemoveConstraint(
            model_name="shacmanhubseo",
            name="shacman_hub_seo_type_facet_unique",
        ),
        migrations.AlterField(
            model_name="shacmanhubseo",
            name="hub_type",
            field=models.CharField(
                choices=_hub_type_choices_after(),
                max_length=32,
                verbose_name="Тип хаба",
            ),
        ),
        migrations.AddConstraint(
            model_name="shacmanhubseo",
            constraint=models.UniqueConstraint(
                condition=Q(facet_key=""),
                fields=("hub_type", "category"),
                name="shacman_hub_seo_type_category_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="shacmanhubseo",
            constraint=models.UniqueConstraint(
                condition=~Q(facet_key=""),
                fields=("hub_type", "category", "facet_key"),
                name="shacman_hub_seo_type_combo_unique",
            ),
        ),
    ]
