# Generated by Django 5.1.15 on 2026-02-02 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0036_shacman_hub_seo_hub_type_max_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shacmanhubseo',
            name='facet_key',
            field=models.CharField(blank=True, default='', help_text='Для formula/engine/line: формула, slug двигателя или линейки. Для combo: line_slug (category_line), «line:formula» (line_formula), formula (category_formula_explicit).', max_length=255, verbose_name='Фасет (formula / engine_slug / line_slug / line:formula)'),
        ),
    ]
