# Generated by Django 5.1.15 on 2026-02-02 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0038_shacmanhubseo_force_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shacmanhubseo',
            name='facet_key',
            field=models.CharField(blank=True, default='', help_text='Для formula/engine/line: формула, slug двигателя или линейки. Для combo: line_slug (category_line), «line:formula» (line_formula, category_line_formula), formula (category_formula_explicit).', max_length=255, verbose_name='Фасет (formula / engine_slug / line_slug / line:formula)'),
        ),
        migrations.AlterField(
            model_name='shacmanhubseo',
            name='hub_type',
            field=models.CharField(choices=[('main', 'Главный хаб /shacman/'), ('in_stock', 'В наличии /shacman/in-stock/'), ('category', 'Категория /shacman/<category>/'), ('category_in_stock', 'Категория в наличии /shacman/<category>/in-stock/'), ('formula', 'Формула /shacman/formula/<formula>/'), ('formula_in_stock', 'Формула в наличии /shacman/formula/<formula>/in-stock/'), ('engine', 'Двигатель /shacman/engine/<engine>/'), ('engine_in_stock', 'Двигатель в наличии /shacman/engine/<engine>/in-stock/'), ('line', 'Линейка /shacman/line/<line>/'), ('line_in_stock', 'Линейка в наличии /shacman/line/<line>/in-stock/'), ('category_line', 'Категория + линейка /shacman/category/<cat>/line/<line>/'), ('category_line_in_stock', 'Категория + линейка в наличии'), ('line_formula', 'Линейка + формула /shacman/line/<line>/formula/<formula>/'), ('line_formula_in_stock', 'Линейка + формула в наличии'), ('category_formula_explicit', 'Категория + формула /shacman/category/<cat>/formula/<formula>/'), ('category_formula_explicit_in_stock', 'Категория + формула в наличии'), ('category_line_formula', 'Категория + линейка + формула /shacman/category/<cat>/line/<line>/formula/<formula>/'), ('category_line_formula_in_stock', 'Категория + линейка + формула в наличии')], max_length=50, verbose_name='Тип хаба'),
        ),
    ]
