# Generated by Django 5.x

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0040_shacmanhubseo_hubtype_choices_v2"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="is_used",
            field=models.BooleanField(
                default=False,
                help_text="Товар с пробегом; отображается на странице /used/ и с бейджем «Б/у».",
                verbose_name="Б/у",
            ),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["is_used", "published"],
                name="product_is_used_published_idx",
            ),
        ),
    ]
